# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -slamam@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Ключ проекта Mammoth55/Job4j
env:
  global:
    - CODECOV_TOKEN="6611891e-76bb-45a5-bd1f-317d3010d6e8"
